name: Check

on:
  workflow_dispatch:
  push:

jobs:
  check:
    runs-on: ubicloud-standard-4

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Check
        run: |
          cargo check --release --all-features
