name: Run the full disk u32 example

on:
  workflow_dispatch:
  # push:

jobs:
  run_test:
    runs-on: ubicloud-standard-4

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo build --release --bin full_disk_u32

      - name: Run
        run: |
          cargo run --release --bin full_disk_u32
